<?php
/* This file is generated by datagen; do not edit. 2016-11-29 00:36:01
== 	id以#id表示	字符串类型	中文字符	描述	数组_含特殊字符，分割符：;,	对象类型，分割符：;，	对象数组，数组；对象， */

return array(
	"m260000" => array(
		"field_1" => "file_111",
		"field_2" => "名字1",
		"field_3" => '描述""特殊字符',
		"field_4" => array(
			"S10101",
			"s10102",
		),
		"field_5" => array(
			"coins" => 50,
			"op" => 2,
		),
		"field_6" => array(
			array(
				"coins" => 50,
			),
			array(
				"op" => 2,
			),
		),
		"id" => "m260000",
	),
	"m260001" => array(
		"field_1" => "file_222",
		"field_2" => "名字2",
		"field_3" => '描述
换行',
		"field_4" => array(
			"S10101",
			"s10103",
		),
		"field_5" => array(
			"coins" => 50,
			"op" => 2,
		),
		"field_6" => array(
			array(
				"coins" => 50,
			),
			array(
				"op" => 2,
			),
		),
		"id" => "m260001",
	),
);

