<?php
/* This file is generated by datagen; do not edit. 2016-11-29 15:23:53
== 	id以#id表示	字符串类型	中文字符	描述	数组_含特殊字符，分割符：;,	对象类型，分割符：;，	对象数组，数组；对象，	外链，使用本身值作为key */

return array(
	"60000" => array(
		"field_1" => "file_111",
		"field_2" => "名字1",
		"field_3" => '描述""特殊字符',
		"field_4" => array(
			"S10101",
			"s10102",
		),
		"field_5" => array(
			"coins" => 50,
			"op" => 2,
		),
		"field_6" => array(
			array(
				"coins" => 50,
			),
			array(
				"op" => 2,
			),
		),
		"id" => 60000,
		"property_1" => array(
			"1" => array(
				"p1" => 200,
				"p2" => array(
					"11" => 1,
					"12" => 2,
					"13" => 3,
					"14" => 4,
					"15" => 5,
				),
				"p3" => array(
					array(
						"buffer" => 4,
						"max" => 11.9,
						"min" => 10.2,
					),
					array(
						"buffer" => 5,
						"max" => 12.9,
						"min" => 11.2,
					),
					array(
						"buffer" => 6,
						"max" => 13.9,
						"min" => 12.2,
					),
					array(
						"buffer" => 7,
						"max" => 14.9,
						"min" => 13.2,
					),
					array(
						"buffer" => 8,
						"max" => 15.9,
						"min" => 14.2,
					),
					array(
						"buffer" => 9,
						"max" => 16.9,
						"min" => 15.2,
					),
					array(
						"buffer" => 10,
						"max" => 17.9,
						"min" => 16.2,
					),
					array(
						"buffer" => 11,
						"max" => 18.9,
						"min" => 17.2,
					),
					array(
						"buffer" => 12,
						"max" => 19.9,
						"min" => 18.2,
					),
					array(
						"buffer" => 13,
						"max" => 20.9,
						"min" => 19.2,
					),
				),
			),
			"2" => array(
				"p1" => 201,
				"p2" => array(
					"11" => 1,
					"12" => 2,
					"13" => 3,
					"14" => 4,
					"15" => 5,
				),
				"p3" => array(
					array(
						"buffer" => 4,
						"max" => 11.9,
						"min" => 10.2,
					),
					array(
						"buffer" => 5,
						"max" => 12.9,
						"min" => 11.2,
					),
					array(
						"buffer" => 6,
						"max" => 13.9,
						"min" => 12.2,
					),
					array(
						"buffer" => 7,
						"max" => 14.9,
						"min" => 13.2,
					),
					array(
						"buffer" => 8,
						"max" => 15.9,
						"min" => 14.2,
					),
					array(
						"buffer" => 9,
						"max" => 16.9,
						"min" => 15.2,
					),
					array(
						"buffer" => 10,
						"max" => 17.9,
						"min" => 16.2,
					),
					array(
						"buffer" => 11,
						"max" => 18.9,
						"min" => 17.2,
					),
					array(
						"buffer" => 12,
						"max" => 19.9,
						"min" => 18.2,
					),
					array(
						"buffer" => 13,
						"max" => 20.9,
						"min" => 19.2,
					),
				),
			),
			"3" => array(
				"p1" => 202,
				"p2" => array(
					"11" => 1,
					"12" => 2,
					"13" => 3,
					"14" => 4,
					"15" => 5,
				),
				"p3" => array(
					array(
						"buffer" => 4,
						"max" => 11.9,
						"min" => 10.2,
					),
					array(
						"buffer" => 5,
						"max" => 12.9,
						"min" => 11.2,
					),
					array(
						"buffer" => 6,
						"max" => 13.9,
						"min" => 12.2,
					),
					array(
						"buffer" => 7,
						"max" => 14.9,
						"min" => 13.2,
					),
					array(
						"buffer" => 8,
						"max" => 15.9,
						"min" => 14.2,
					),
					array(
						"buffer" => 9,
						"max" => 16.9,
						"min" => 15.2,
					),
					array(
						"buffer" => 10,
						"max" => 17.9,
						"min" => 16.2,
					),
					array(
						"buffer" => 11,
						"max" => 18.9,
						"min" => 17.2,
					),
					array(
						"buffer" => 12,
						"max" => 19.9,
						"min" => 18.2,
					),
					array(
						"buffer" => 13,
						"max" => 20.9,
						"min" => 19.2,
					),
				),
			),
			"4" => array(
				"p1" => 203,
				"p2" => array(
					"11" => 1,
					"12" => 2,
					"13" => 3,
					"14" => 4,
					"15" => 6,
				),
				"p3" => array(
					array(
						"buffer" => 4,
						"max" => 11.9,
						"min" => 10.2,
					),
					array(
						"buffer" => 5,
						"max" => 12.9,
						"min" => 11.2,
					),
					array(
						"buffer" => 6,
						"max" => 13.9,
						"min" => 12.2,
					),
					array(
						"buffer" => 7,
						"max" => 14.9,
						"min" => 13.2,
					),
					array(
						"buffer" => 8,
						"max" => 15.9,
						"min" => 14.2,
					),
					array(
						"buffer" => 9,
						"max" => 16.9,
						"min" => 15.2,
					),
					array(
						"buffer" => 10,
						"max" => 17.9,
						"min" => 16.2,
					),
					array(
						"buffer" => 11,
						"max" => 18.9,
						"min" => 17.2,
					),
					array(
						"buffer" => 12,
						"max" => 19.9,
						"min" => 18.2,
					),
					array(
						"buffer" => 13,
						"max" => 20.9,
						"min" => 19.2,
					),
				),
			),
		),
	),
	"60001" => array(
		"field_1" => "file_222",
		"field_2" => "名字2",
		"field_3" => '描述
换行',
		"field_4" => array(
			"S10101",
			"s10103",
		),
		"field_5" => array(
			"coins" => 50,
			"op" => 2,
		),
		"field_6" => array(
			array(
				"coins" => 50,
			),
			array(
				"op" => 2,
			),
		),
		"id" => 60001,
		"property_1" => array(
			"1" => array(
				"p1" => 200,
				"p2" => array(
					"11" => 1,
					"12" => 2,
					"13" => 3,
					"14" => 4,
					"15" => 6,
				),
				"p3" => array(
					array(
						"buffer" => 4,
						"max" => 11.9,
						"min" => 10.2,
					),
					array(
						"buffer" => 5,
						"max" => 12.9,
						"min" => 11.2,
					),
					array(
						"buffer" => 6,
						"max" => 13.9,
						"min" => 12.2,
					),
					array(
						"buffer" => 7,
						"max" => 14.9,
						"min" => 13.2,
					),
					array(
						"buffer" => 8,
						"max" => 15.9,
						"min" => 14.2,
					),
					array(
						"buffer" => 9,
						"max" => 16.9,
						"min" => 15.2,
					),
					array(
						"buffer" => 10,
						"max" => 17.9,
						"min" => 16.2,
					),
					array(
						"buffer" => 11,
						"max" => 18.9,
						"min" => 17.2,
					),
					array(
						"buffer" => 12,
						"max" => 19.9,
						"min" => 18.2,
					),
					array(
						"buffer" => 13,
						"max" => 20.9,
						"min" => 19.2,
					),
				),
			),
			"2" => array(
				"p1" => 201,
				"p2" => array(
					"11" => 1,
					"12" => 2,
					"13" => 3,
					"14" => 4,
					"15" => 6,
				),
				"p3" => array(
					array(
						"buffer" => 4,
						"max" => 11.9,
						"min" => 10.2,
					),
					array(
						"buffer" => 5,
						"max" => 12.9,
						"min" => 11.2,
					),
					array(
						"buffer" => 6,
						"max" => 13.9,
						"min" => 12.2,
					),
					array(
						"buffer" => 7,
						"max" => 14.9,
						"min" => 13.2,
					),
					array(
						"buffer" => 8,
						"max" => 15.9,
						"min" => 14.2,
					),
					array(
						"buffer" => 9,
						"max" => 16.9,
						"min" => 15.2,
					),
					array(
						"buffer" => 10,
						"max" => 17.9,
						"min" => 16.2,
					),
					array(
						"buffer" => 11,
						"max" => 18.9,
						"min" => 17.2,
					),
					array(
						"buffer" => 12,
						"max" => 19.9,
						"min" => 18.2,
					),
					array(
						"buffer" => 13,
						"max" => 20.9,
						"min" => 19.2,
					),
				),
			),
			"3" => array(
				"p1" => 202,
				"p2" => array(
					"11" => 1,
					"12" => 2,
					"13" => 3,
					"14" => 4,
					"15" => 7,
				),
				"p3" => array(
					array(
						"buffer" => 4,
						"max" => 11.9,
						"min" => 10.2,
					),
					array(
						"buffer" => 5,
						"max" => 12.9,
						"min" => 11.2,
					),
					array(
						"buffer" => 6,
						"max" => 13.9,
						"min" => 12.2,
					),
					array(
						"buffer" => 7,
						"max" => 14.9,
						"min" => 13.2,
					),
					array(
						"buffer" => 8,
						"max" => 15.9,
						"min" => 14.2,
					),
					array(
						"buffer" => 9,
						"max" => 16.9,
						"min" => 15.2,
					),
					array(
						"buffer" => 10,
						"max" => 17.9,
						"min" => 16.2,
					),
					array(
						"buffer" => 11,
						"max" => 18.9,
						"min" => 17.2,
					),
					array(
						"buffer" => 12,
						"max" => 19.9,
						"min" => 18.2,
					),
					array(
						"buffer" => 13,
						"max" => 20.9,
						"min" => 19.2,
					),
				),
			),
			"4" => array(
				"p1" => 203,
				"p2" => array(
					"11" => 1,
					"12" => 2,
					"13" => 3,
					"14" => 4,
					"15" => 7,
				),
				"p3" => array(
					array(
						"buffer" => 4,
						"max" => 11.9,
						"min" => 10.2,
					),
					array(
						"buffer" => 5,
						"max" => 12.9,
						"min" => 11.2,
					),
					array(
						"buffer" => 6,
						"max" => 13.9,
						"min" => 12.2,
					),
					array(
						"buffer" => 7,
						"max" => 14.9,
						"min" => 13.2,
					),
					array(
						"buffer" => 8,
						"max" => 15.9,
						"min" => 14.2,
					),
					array(
						"buffer" => 9,
						"max" => 16.9,
						"min" => 15.2,
					),
					array(
						"buffer" => 10,
						"max" => 17.9,
						"min" => 16.2,
					),
					array(
						"buffer" => 11,
						"max" => 18.9,
						"min" => 17.2,
					),
					array(
						"buffer" => 12,
						"max" => 19.9,
						"min" => 18.2,
					),
					array(
						"buffer" => 13,
						"max" => 20.9,
						"min" => 19.2,
					),
				),
			),
		),
	),
);

